name: Pull request Workflow

on:
  pull_request:
# this will cancel any running jobs for a PR when new commits are made..
concurrency:
  group: 'testingConcurrency'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Action to check out your repository's code

      - name: Install Python 3.11
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Run Tests with Poetry
        run: |
          poetry install
          cd steps && poetry run python test_commonSteps.py

  build2:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Run Tests with Poetry
        run: |
          poetry install
          cd steps && poetry run python test_commonSteps.py